-- Versioned Terms and Conditions / Privacy Notice acceptance records.
-- The document text is source-controlled in the application; this migration
-- stores the published version metadata and the user's acceptance audit trail.

create table if not exists legal_documents (
  id bigint generated by default as identity primary key,
  document_type text not null check (document_type in ('terms', 'privacy')),
  version text not null,
  title text not null,
  effective_at timestamptz not null,
  content_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (document_type, version)
);

create unique index if not exists legal_documents_one_active_per_type
  on legal_documents (document_type)
  where is_active = true;

create table if not exists legal_acceptances (
  id bigint generated by default as identity primary key,
  account_id bigint not null references accounts(id) on delete cascade,
  legal_document_id bigint not null references legal_documents(id) on delete restrict,
  document_type text not null check (document_type in ('terms', 'privacy')),
  document_version text not null,
  accepted_at timestamptz not null default now(),
  acceptance_method text not null default 'explicit_checkbox',
  ip_address inet,
  user_agent text,
  unique (account_id, legal_document_id)
);

create index if not exists legal_acceptances_account_idx
  on legal_acceptances (account_id, document_type, document_version);

alter table public.legal_documents enable row level security;
alter table public.legal_acceptances enable row level security;

insert into legal_documents
  (document_type, version, title, effective_at, content_hash, is_active)
values
  ('terms', '2026.08.26', 'PNP-ITMS Terms and Conditions', '2026-08-26T00:00:00Z', 'pnp-itms-terms-2026.08.26', true),
  ('privacy', '2026.08.26', 'PNP-ITMS Privacy Notice', '2026-08-26T00:00:00Z', 'pnp-itms-privacy-2026.08.26', true)
on conflict (document_type, version) do update set
  title = excluded.title,
  effective_at = excluded.effective_at,
  content_hash = excluded.content_hash,
  is_active = excluded.is_active;
