-- Migration: Superadmin Attendance Control and DTR Management
-- Tables: attendance_profiles, account_attendance_profiles, attendance_records, dtr_edit_history
-- Updates: accounts.role check constraint, attendance_logs columns

BEGIN;

-- 1. Update accounts table role check constraint to include 'superadmin'
DO $$
BEGIN
  ALTER TABLE public.accounts DROP CONSTRAINT IF EXISTS accounts_role_check;
  ALTER TABLE public.accounts ADD CONSTRAINT accounts_role_check
    CHECK (role IN ('superadmin', 'admin', 'supervisor', 'intern'));
EXCEPTION
  WHEN others THEN NULL;
END $$;

-- 2. Create attendance_profiles table
CREATE TABLE IF NOT EXISTS public.attendance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_name text NOT NULL,
  time_in time NOT NULL DEFAULT '08:00:00',
  time_out time NOT NULL DEFAULT '17:00:00',
  first_scan_enabled boolean NOT NULL DEFAULT true,
  second_scan_enabled boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Create account_attendance_profiles table
CREATE TABLE IF NOT EXISTS public.account_attendance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  attendance_profile_id bigint NOT NULL REFERENCES public.attendance_profiles(id) ON DELETE CASCADE,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  UNIQUE (account_id)
);

-- 4. Create attendance_records table
CREATE TABLE IF NOT EXISTS public.attendance_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  attendance_date date NOT NULL,
  actual_time_in timestamptz,
  recorded_time_in timestamptz,
  actual_time_out timestamptz,
  recorded_time_out timestamptz,
  attendance_profile_id bigint REFERENCES public.attendance_profiles(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (account_id, attendance_date)
);

-- 5. Create dtr_edit_history table
CREATE TABLE IF NOT EXISTS public.dtr_edit_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id bigint REFERENCES public.attendance_records(id) ON DELETE CASCADE,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  field_name text NOT NULL,
  original_value text,
  new_value text,
  modified_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  modified_at timestamptz NOT NULL DEFAULT now(),
  reason text NOT NULL
);

-- 6. Add columns to attendance_logs
ALTER TABLE public.attendance_logs
  ADD COLUMN IF NOT EXISTS actual_scan_time timestamptz,
  ADD COLUMN IF NOT EXISTS recorded_scan_time timestamptz,
  ADD COLUMN IF NOT EXISTS attendance_profile_id bigint REFERENCES public.attendance_profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS attendance_record_id bigint REFERENCES public.attendance_records(id) ON DELETE SET NULL;

-- 7. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_account_attendance_profiles_profile
  ON public.account_attendance_profiles(attendance_profile_id);

CREATE INDEX IF NOT EXISTS idx_attendance_records_account_date
  ON public.attendance_records(account_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_dtr_edit_history_account_record
  ON public.dtr_edit_history(account_id, attendance_record_id);

CREATE INDEX IF NOT EXISTS idx_dtr_edit_history_modified_at
  ON public.dtr_edit_history(modified_at DESC);

CREATE INDEX IF NOT EXISTS idx_attendance_logs_account_profile
  ON public.attendance_logs(attendance_profile_id);

-- 8. Seed Default "Regular 8AM–5PM" Profile
INSERT INTO public.attendance_profiles (profile_name, time_in, time_out, first_scan_enabled, second_scan_enabled, status)
SELECT 'Regular 8AM–5PM', '08:00:00'::time, '17:00:00'::time, true, true, 'active'
WHERE NOT EXISTS (
  SELECT 1 FROM public.attendance_profiles WHERE profile_name = 'Regular 8AM–5PM'
);

-- 9. Seed Default Superadmin Account (if none exists)
INSERT INTO public.accounts (username, password_hash, full_name, email, role)
SELECT
  'superadmin',
  '$2a$10$StKL8H7szIFcq28NI.IwKewDMiE1qKwo6iPgZIFqmQEykMlJTvVpq', -- password: 'password'
  'Super Administrator',
  'superadmin@pnp-itms.gov.ph',
  'superadmin'
WHERE NOT EXISTS (
  SELECT 1 FROM public.accounts WHERE username = 'superadmin' OR role = 'superadmin'
);

-- 10. Enable RLS
ALTER TABLE public.attendance_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_attendance_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dtr_edit_history ENABLE ROW LEVEL SECURITY;

-- Allow authenticated reads for attendance profiles
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'attendance_profiles' AND policyname = 'Allow authenticated read profiles'
  ) THEN
    CREATE POLICY "Allow authenticated read profiles"
      ON public.attendance_profiles FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END $$;

-- Allow superadmin full access to attendance profiles
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'attendance_profiles' AND policyname = 'Allow superadmin manage profiles'
  ) THEN
    CREATE POLICY "Allow superadmin manage profiles"
      ON public.attendance_profiles FOR ALL
      TO authenticated
      USING ((SELECT role FROM public.accounts WHERE email = auth.email()) = 'superadmin')
      WITH CHECK ((SELECT role FROM public.accounts WHERE email = auth.email()) = 'superadmin');
  END IF;
END $$;

COMMIT;
