-- Audited face enrollment and one-time renewal approval workflow.
-- Run this after migration_face_verification.sql.

CREATE TABLE IF NOT EXISTS face_renewal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intern_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  intern_name text NOT NULL,
  reason text NOT NULL CHECK (char_length(trim(reason)) BETWEEN 10 AND 500),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'completed')),
  reviewed_by bigint REFERENCES accounts(id) ON DELETE SET NULL,
  reviewer_name text,
  review_remarks text,
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS face_enrollment_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intern_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  intern_name text NOT NULL,
  enrollment_type text NOT NULL CHECK (enrollment_type IN ('initial', 'renewal')),
  renewal_reason text NOT NULL,
  request_id bigint REFERENCES face_renewal_requests(id) ON DELETE SET NULL,
  enrolled_by bigint REFERENCES accounts(id) ON DELETE SET NULL,
  enrolled_by_name text NOT NULL,
  enrolled_by_role text NOT NULL CHECK (enrolled_by_role IN ('admin', 'supervisor', 'intern')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_face_renewal_request_open
  ON face_renewal_requests (intern_id)
  WHERE status IN ('pending', 'approved');

CREATE INDEX IF NOT EXISTS idx_face_renewal_requests_status_created
  ON face_renewal_requests (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_face_renewal_requests_intern
  ON face_renewal_requests (intern_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_face_enrollment_history_intern
  ON face_enrollment_history (intern_id, created_at DESC);

INSERT INTO face_enrollment_history (
  intern_id,
  intern_name,
  enrollment_type,
  renewal_reason,
  enrolled_by,
  enrolled_by_name,
  enrolled_by_role,
  created_at
)
SELECT
  account.id,
  account.full_name,
  'initial',
  'Existing biometric enrollment imported during audit-history migration',
  NULL,
  'Legacy enrollment (imported)',
  'admin',
  coalesce(account.face_registered_at, now())
FROM accounts account
WHERE account.role = 'intern'
  AND account.face_registered = true
  AND NOT EXISTS (
    SELECT 1
    FROM face_enrollment_history history
    WHERE history.intern_id = account.id
  );

ALTER TABLE face_renewal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE face_enrollment_history ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON face_renewal_requests FROM anon, authenticated;
REVOKE ALL ON face_enrollment_history FROM anon, authenticated;
GRANT ALL ON face_renewal_requests TO service_role;
GRANT ALL ON face_enrollment_history TO service_role;
GRANT USAGE, SELECT ON SEQUENCE face_renewal_requests_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE face_enrollment_history_id_seq TO service_role;

CREATE OR REPLACE FUNCTION complete_face_enrollment(
  p_intern_id bigint,
  p_embedding jsonb,
  p_photo text,
  p_actor_id bigint,
  p_reason text,
  p_request_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_intern accounts%ROWTYPE;
  v_actor accounts%ROWTYPE;
  v_request face_renewal_requests%ROWTYPE;
  v_type text;
  v_now timestamptz := now();
  v_history_id bigint;
BEGIN
  SELECT * INTO v_intern
  FROM accounts
  WHERE id = p_intern_id AND role = 'intern'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Intern account not found';
  END IF;

  SELECT * INTO v_actor
  FROM accounts
  WHERE id = p_actor_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Enrollment actor not found';
  END IF;

  IF p_embedding IS NULL OR p_photo IS NULL THEN
    RAISE EXCEPTION 'Face embedding and enrollment photo are required';
  END IF;

  IF char_length(trim(coalesce(p_reason, ''))) < 10
     OR char_length(trim(coalesce(p_reason, ''))) > 500 THEN
    RAISE EXCEPTION 'Enrollment reason must be between 10 and 500 characters';
  END IF;

  IF p_request_id IS NULL THEN
    IF v_actor.role NOT IN ('admin', 'supervisor') THEN
      RAISE EXCEPTION 'Initial or direct enrollment requires authorized staff';
    END IF;

    IF v_actor.role = 'supervisor'
       AND (v_actor.division_id IS NULL OR v_actor.division_id IS DISTINCT FROM v_intern.division_id) THEN
      RAISE EXCEPTION 'Supervisor cannot enroll an intern from another division';
    END IF;

    IF v_intern.face_registered
       AND EXISTS (
         SELECT 1
         FROM face_renewal_requests
         WHERE intern_id = p_intern_id
           AND status IN ('pending', 'approved')
       ) THEN
      RAISE EXCEPTION 'Resolve the intern''s active renewal request before a direct staff replacement';
    END IF;
  ELSE
    SELECT * INTO v_request
    FROM face_renewal_requests
    WHERE id = p_request_id
    FOR UPDATE;

    IF NOT FOUND
       OR v_request.intern_id IS DISTINCT FROM p_intern_id
       OR v_request.status <> 'approved' THEN
      RAISE EXCEPTION 'This renewal approval is invalid or has already been used';
    END IF;

    IF v_actor.id <> p_intern_id OR v_actor.role <> 'intern' THEN
      RAISE EXCEPTION 'Only the approved intern may complete this renewal';
    END IF;
  END IF;

  v_type := CASE WHEN v_intern.face_registered THEN 'renewal' ELSE 'initial' END;

  UPDATE accounts
  SET face_embedding = p_embedding,
      face_photo = p_photo,
      face_registered = true,
      face_registered_at = v_now
  WHERE id = p_intern_id;

  INSERT INTO face_enrollment_history (
    intern_id,
    intern_name,
    enrollment_type,
    renewal_reason,
    request_id,
    enrolled_by,
    enrolled_by_name,
    enrolled_by_role,
    created_at
  )
  VALUES (
    v_intern.id,
    v_intern.full_name,
    v_type,
    trim(p_reason),
    p_request_id,
    v_actor.id,
    v_actor.full_name,
    v_actor.role,
    v_now
  )
  RETURNING id INTO v_history_id;

  IF p_request_id IS NOT NULL THEN
    UPDATE face_renewal_requests
    SET status = 'completed',
        completed_at = v_now,
        updated_at = v_now
    WHERE id = p_request_id;
  END IF;

  RETURN jsonb_build_object(
    'id', v_intern.id,
    'full_name', v_intern.full_name,
    'email', v_intern.email,
    'face_registered', true,
    'face_registered_at', v_now,
    'enrollment_type', v_type,
    'history_id', v_history_id,
    'request_id', p_request_id
  );
END;
$$;

REVOKE ALL ON FUNCTION complete_face_enrollment(bigint, jsonb, text, bigint, text, bigint)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION complete_face_enrollment(bigint, jsonb, text, bigint, text, bigint)
  TO service_role;
