-- Migration: Attendance Attachments for Super Admin Manual Uploads
-- Table: attendance_attachments

BEGIN;

CREATE TABLE IF NOT EXISTS public.attendance_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id bigint NOT NULL,
  image_url text NOT NULL,
  file_name text,
  original_filename text,
  mime_type text,
  file_size bigint,
  storage_path text,
  uploaded_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  uploaded_by_name text,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (attendance_id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_attachments_attendance_id ON public.attendance_attachments (attendance_id);

COMMIT;
