-- Role-aware project visibility, normalized membership, private files,
-- archive/restore, and project audit history.
-- Run after migration_project_authorization.sql.

BEGIN;

ALTER TABLE public.intern_projects
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS archived_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS archive_reason text;

CREATE TABLE IF NOT EXISTS public.project_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.intern_projects(id) ON DELETE CASCADE,
  account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  project_role text NOT NULL DEFAULT 'member' CHECK (project_role IN ('leader', 'member')),
  added_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  joined_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  UNIQUE (project_id, account_id)
);

CREATE TABLE IF NOT EXISTS public.project_contributors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.intern_projects(id) ON DELETE CASCADE,
  display_name text NOT NULL CHECK (char_length(trim(display_name)) BETWEEN 1 AND 200),
  added_by bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint REFERENCES public.intern_projects(id) ON DELETE SET NULL,
  actor_id bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
  actor_name text NOT NULL,
  actor_role text NOT NULL CHECK (actor_role IN ('admin', 'supervisor', 'intern')),
  action text NOT NULL CHECK (action IN (
    'created', 'updated', 'archived', 'restored', 'deleted',
    'file_uploaded', 'file_deleted'
  )),
  changes jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_project_members_account
  ON public.project_members(account_id, project_id)
  WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_project_members_project
  ON public.project_members(project_id)
  WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_project_contributors_project
  ON public.project_contributors(project_id);
CREATE INDEX IF NOT EXISTS idx_project_audit_project_created
  ON public.project_audit_log(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intern_projects_archived
  ON public.intern_projects(archived_at, updated_at DESC);

-- Preserve leaders as normalized team members.
INSERT INTO public.project_members (project_id, account_id, project_role, joined_at)
SELECT project.id, project.leader_id, 'leader', project.created_at
FROM public.intern_projects project
JOIN public.accounts account
  ON account.id = project.leader_id
 AND account.role = 'intern'
WHERE project.leader_id IS NOT NULL
ON CONFLICT (project_id, account_id)
DO UPDATE SET project_role = 'leader', removed_at = NULL;

-- Preserve valid account-backed members from the previous JSON array.
INSERT INTO public.project_members (project_id, account_id, project_role, joined_at)
SELECT DISTINCT
  project.id,
  account.id,
  CASE WHEN account.id = project.leader_id THEN 'leader' ELSE 'member' END,
  project.created_at
FROM public.intern_projects project
CROSS JOIN LATERAL jsonb_array_elements(coalesce(project.members, '[]'::jsonb)) member
JOIN public.accounts account
  ON account.id = CASE
    WHEN member->>'id' ~ '^[0-9]+$' THEN (member->>'id')::bigint
    ELSE NULL
  END
 AND account.role = 'intern'
ON CONFLICT (project_id, account_id)
DO UPDATE SET removed_at = NULL;

-- Keep typed or otherwise non-account contributors for display only.
INSERT INTO public.project_contributors (project_id, display_name, created_at)
SELECT DISTINCT
  project.id,
  trim(coalesce(member->>'full_name', member->>'name')),
  project.created_at
FROM public.intern_projects project
CROSS JOIN LATERAL jsonb_array_elements(coalesce(project.members, '[]'::jsonb)) member
LEFT JOIN public.accounts account
  ON account.id = CASE
    WHEN member->>'id' ~ '^[0-9]+$' THEN (member->>'id')::bigint
    ELSE NULL
  END
WHERE account.id IS NULL
  AND char_length(trim(coalesce(member->>'full_name', member->>'name', ''))) BETWEEN 1 AND 200
  AND NOT EXISTS (
    SELECT 1
    FROM public.project_contributors existing
    WHERE existing.project_id = project.id
      AND lower(existing.display_name) = lower(trim(coalesce(member->>'full_name', member->>'name')))
  );

ALTER TABLE public.project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_contributors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_audit_log ENABLE ROW LEVEL SECURITY;

-- The application uses its Express API for mutations. Remove broad direct
-- mutation policies so browser clients cannot bypass API authorization.
DROP POLICY IF EXISTS "Allow all authenticated users to read projects" ON public.intern_projects;
DROP POLICY IF EXISTS "Authorized users can create projects" ON public.intern_projects;
DROP POLICY IF EXISTS "Authorized users can update projects" ON public.intern_projects;
DROP POLICY IF EXISTS "Authorized users can delete projects" ON public.intern_projects;
DROP POLICY IF EXISTS "Allow all authenticated users to read project files" ON public.project_files;
DROP POLICY IF EXISTS "Authorized users can upload project files" ON public.project_files;
DROP POLICY IF EXISTS "Authorized users can delete project files" ON public.project_files;

CREATE OR REPLACE FUNCTION public.can_access_intern_project(p_project_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.accounts me
    JOIN public.intern_projects project ON project.id = p_project_id
    WHERE me.email = auth.email()
      AND coalesce(lower(me.status), 'active') NOT IN ('inactive', 'disabled', 'archived')
      AND (
        me.role = 'admin'
        OR (me.role = 'supervisor' AND project.division_id = me.division_id)
        OR (
          me.role = 'intern'
          AND (
            project.leader_id = me.id
            OR EXISTS (
              SELECT 1
              FROM public.project_members membership
              WHERE membership.project_id = project.id
                AND membership.account_id = me.id
                AND membership.removed_at IS NULL
            )
          )
        )
      )
  );
$$;

REVOKE ALL ON FUNCTION public.can_access_intern_project(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_access_intern_project(bigint) TO authenticated, service_role;

CREATE POLICY "Role scoped project reads"
ON public.intern_projects FOR SELECT TO authenticated
USING (public.can_access_intern_project(id));

CREATE POLICY "Role scoped project file reads"
ON public.project_files FOR SELECT TO authenticated
USING (public.can_access_intern_project(project_id));

CREATE POLICY "Role scoped membership reads"
ON public.project_members FOR SELECT TO authenticated
USING (public.can_access_intern_project(project_id));

CREATE POLICY "Role scoped contributor reads"
ON public.project_contributors FOR SELECT TO authenticated
USING (public.can_access_intern_project(project_id));

CREATE POLICY "Leader and staff audit reads"
ON public.project_audit_log FOR SELECT TO authenticated
USING (
  public.can_access_intern_project(project_id)
  AND EXISTS (
    SELECT 1
    FROM public.accounts me
    JOIN public.intern_projects project ON project.id = project_audit_log.project_id
    WHERE me.email = auth.email()
      AND (
        me.role = 'admin'
        OR (me.role = 'supervisor' AND me.division_id = project.division_id)
        OR (me.role = 'intern' AND me.id = project.leader_id)
      )
  )
);

GRANT ALL ON public.project_members TO service_role;
GRANT ALL ON public.project_contributors TO service_role;
GRANT ALL ON public.project_audit_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.project_members_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.project_contributors_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.project_audit_log_id_seq TO service_role;

-- Existing documents and project deliverables share this bucket. The backend
-- now returns short-lived signed URLs for both, so the bucket can be private.
UPDATE storage.buckets
SET public = false
WHERE id = 'documents';

NOTIFY pgrst, 'reload schema';

COMMIT;
