-- Supabase table schema for accounts

create table if not exists accounts (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  full_name text not null,
  email text not null unique,
  role text not null check (role in ('admin','intern')),
  school text,
  course text,
  department_id bigint,
  department_name text,
  student_id text,
  year_level text,
  status text default 'active',
  start_date date,
  end_date date,
  required_hours numeric default 486,
  rendered_hours numeric default 0,
  phone text,
  home_address text,
  emergency_name text,
  emergency_relation text,
  emergency_phone text,
  created_at timestamptz not null default now()
);

-- Department management table
create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  head_name text,
  created_at timestamptz not null default now()
);

-- Supabase table for generated office QR codes
create table if not exists qr_codes (
  id bigint generated by default as identity primary key,
  qr_code text not null unique,
  is_active boolean not null default true,
  generated_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- Supabase table for attendance logs
create table if not exists attendance_logs (
  id bigint generated by default as identity primary key,
  intern_id bigint,
  intern_name text,
  scan_type text not null check (scan_type in ('time_in','time_out')),
  scan_time timestamptz not null,
  qr_code_id bigint,
  approval_status text not null default 'pending' check (approval_status in ('pending','approved','rejected')),
  remarks text,
  created_at timestamptz not null default now()
);

-- Documents uploaded by interns
create table if not exists documents (
  id bigint generated by default as identity primary key,
  intern_id bigint not null,
  document_type text not null,
  original_name text not null,
  file_name text not null,
  file_type text not null,
  file_size bigint not null,
  file_path text not null,
  upload_date timestamptz not null default now(),
  status text not null default 'pending',
  admin_remarks text,
  created_at timestamptz not null default now()
);

-- Evaluation records for interns
create table if not exists evaluations (
  id bigint generated by default as identity primary key,
  intern_id bigint not null,
  evaluator_id bigint not null,
  evaluator_name text not null,
  evaluation_date timestamptz not null default now(),
  overall_score numeric not null,
  overall_rating text not null,
  comments text,
  work_quality numeric,
  punctuality numeric,
  teamwork numeric,
  communication numeric,
  initiative numeric,
  created_at timestamptz not null default now()
);

-- Notifications for users
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Example seed data for admin and intern users (password = "password")
insert into accounts (username, password_hash, full_name, email, role)
values
  ('admin', '$2a$10$8DA752LK9rXg3ejo67sfJOhWxQHeEkjlpDv5PxMFTfVhrG7.h1Y6O', 'Demo Admin', 'admin@pnp-itms.gov.ph', 'admin'),
  ('intern', '$2a$10$fiRc0kvZGC4cQmYQmnbJfunN7PYDRH2tNA0m0kTyo3YkCCQ03Ckm.', 'Demo Intern', 'intern@pnp-itms.gov.ph', 'intern');
