-- Supabase table schema for accounts

create table if not exists accounts (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  full_name text not null,
  email text not null unique,
  role text not null check (role in ('admin','intern')),
  created_at timestamptz not null default now()
);

-- Example seed data for admin and intern users (password = "password")
insert into accounts (username, password_hash, full_name, email, role)
values
  ('admin', '$2a$10$8DA752LK9rXg3ejo67sfJOhWxQHeEkjlpDv5PxMFTfVhrG7.h1Y6O', 'Demo Admin', 'admin@pnp-itms.gov.ph', 'admin'),
  ('intern', '$2a$10$fiRc0kvZGC4cQmYQmnbJfunN7PYDRH2tNA0m0kTyo3YkCCQ03Ckm.', 'Demo Intern', 'intern@pnp-itms.gov.ph', 'intern');
